### ISSUE TITLE
Glow maps

### ISSUE THREAD

**Issue by h2g2guy** [GGP-Null/discs#28]
Grayscale maps of where the textures should glow.

**Comment by KevinMGranger** [comment]
![](http://imgusr.tradekey.com/p-B172130-20110129073930/glow-hat-retail-1pk.jpg)

**Comment by KevinMGranger** [comment]
![](http://g01.a.alicdn.com/kf/HTB1WtFUIpXXXXXJXpXXq6xXFXXXN/Promotion-Only-10pcs-Available-Night-Glow-Luminous-Eminem-Letter-Logo-Print-Women-Swag-T-shirt-Glowing.jpg)

**Comment by KevinMGranger** [comment]
![](https://i.ytimg.com/vi/-fOZaVmbKxc/hqdefault.jpg)
